# Generated by Django 4.0.3 on 2022-04-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regform',
            name='uniqueid',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regform',
            name='name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
