# Generated by Django 4.0.3 on 2022-04-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_regform_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('blood', models.CharField(max_length=3)),
                ('pin', models.IntegerField()),
                ('uniqueid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=50)),
                ('datetime', models.CharField(max_length=50)),
                ('visit', models.CharField(max_length=250)),
                ('medications', models.CharField(max_length=250)),
            ],
        ),
    ]
