# Generated by Django 4.0.3 on 2022-04-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_detailform_medical'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailform',
            name='sex',
            field=models.CharField(default='12:30', max_length=10),
            preserve_default=False,
        ),
    ]
