# Generated by Django 4.0.3 on 2022-04-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_detailform_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='uniqueid',
            field=models.CharField(default=120, max_length=20),
            preserve_default=False,
        ),
    ]
